title: Football Atlas
description: Where football meets the world.
baseurl: "" # leave empty or put your site base URL if hosted in a subdirectory
url: "https://yourusername.github.io" # replace with your GitHub Pages URL or custom domain

theme: jekyll-theme-primer

plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-relative-links
  - jekyll-readme-index

paginate: 10

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

markdown: kramdown

kramdown:
  input: GFM
